In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
a.shape

(4,)

In [6]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
print(b.shape)

(2, 4)


In [8]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [9]:
np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

In [10]:
np.random.randint(60,100,10)
#(StartLimit inculuded, EndLimit excluded, Number of total elements)

array([73, 66, 78, 88, 93, 97, 92, 86, 80, 99])

In [11]:
matrix = np.random.randint(60,100,(5,5))
#(StartLimit inculuded, EndLimit excluded, A matrix of size 5x5)
print(matrix)

[[74 97 62 97 90]
 [73 93 67 61 61]
 [74 61 66 85 74]
 [89 85 88 85 86]
 [62 94 62 91 91]]


In [12]:
np.max(matrix)
# It gives the maximum element present in the matrix.

97

In [13]:
print(a)

[1 2 3 4]


In [22]:
a = np.array([0,1,2,3,6,8,10,8,8,8])

In [23]:
np.argmin(a) #It gives the index where the minimum element is present

0

In [24]:
print(np.unique(a))

[ 0  1  2  3  6  8 10]


In [25]:
print(np.unique(a,return_counts=True))

(array([ 0,  1,  2,  3,  6,  8, 10]), array([1, 1, 1, 1, 1, 4, 1], dtype=int64))


In [26]:
b = np.unique(a,return_counts=True)
# It returns all the unique elements present in the array as an array.
print(b)
# It returns a tuple of arrays.

(array([ 0,  1,  2,  3,  6,  8, 10]), array([1, 1, 1, 1, 1, 4, 1], dtype=int64))


In [27]:
print(b[0])
# It prints a list of unique elements.

[ 0  1  2  3  6  8 10]


In [28]:
print(b[1])
# It consist of count of unique elements

[1 1 1 1 1 4 1]


In [29]:
#Program to find out the number with the highest frequency in the array
b = np.unique(a,return_counts=True)
idx = np.argmax(b[1])
element = b[0][idx]
print(element)

8


In [30]:
#Slicing Arrays
matrix

array([[74, 97, 62, 97, 90],
       [73, 93, 67, 61, 61],
       [74, 61, 66, 85, 74],
       [89, 85, 88, 85, 86],
       [62, 94, 62, 91, 91]])

In [31]:
matrix[2:4,1:4]

array([[61, 66, 85],
       [85, 88, 85]])

In [32]:
matrix[0][0]

74