In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)#(5,) i.e. it is a linear array
print(a[0])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1


In [6]:
# for 4*3 matrix we have (4,3) shape of the numpy.ndarray

In [9]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)# 2-d array
print(b.shape)
print(b[0][0])

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
1


In [10]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
c[1][1]

[[1 2 3]
 [4 5 6]]
(2, 3)


5

In [18]:
# Create Zeros, Ones, Custom array
a = np.zeros((3,3))
print(a) # An array of 0s of size 3*3

b = np.ones((2,3))
print(b) # An array of 1s of size 2*3

#Array of some constants
#c = np.full((r,c),val)
c = np.full((3,2),5)
print(c)

#Identity Matrix - Size/Square matrix
d = np.eye(4)
print(d)

#Random Matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.76559187 0.75281503 0.53466055]
 [0.73483731 0.8702638  0.13389198]]


In [19]:
print(randomMatrix[:,1])
#we need all the rows so no starting and ending values for rows and we need the column 1 so 1

[0.75281503 0.8702638 ]


In [21]:
print(randomMatrix[:,2])
#for second column

[0.53466055 0.13389198]


In [24]:
print(randomMatrix[1,1:3]) #Slicing

[0.8702638  0.13389198]


In [26]:
print(randomMatrix[1,1:])
#select the last two column values of the last row

[0.8702638  0.13389198]


In [27]:
randomMatrix[1,1:] = 1

In [28]:
print(randomMatrix)

[[0.76559187 0.75281503 0.53466055]
 [0.73483731 1.         1.        ]]


In [32]:
## Set some rows and columns with any values
z = np.zeros((3,3))
print(z)
z[1,:]=5
z[:,-1] = 7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [31]:
#Fill middle rows with 5 and last column with 7

In [33]:
# Datatypes
print(z.dtype)

float64


In [36]:
#If I have to convert the data type of the matrix to int

In [37]:
## Set some rows and columns with any values
z = np.zeros((3,3), dtype= np.int64)
print(z)
z[1,:]=5
z[:,-1] = 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [38]:
print(z.dtype)

int64


In [40]:
#Mathematical Operations

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
#Element wise addition
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [41]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [42]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [43]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [44]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [46]:
#Matrix Multiplication / Dot Products
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [47]:
#Multiplication(Dot Product) of Vectors - Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [48]:
print(a)

[1 2 3 4]


In [49]:
print(sum(a))

10


In [52]:
print(np.sum(a))
print(np.sum(x,axis=0))#column wise sum

10
[4 6]


In [53]:
print(np.sum(x,axis=1))#row wise sum

[3 7]


In [57]:
# Stacking of arrays
print(a)
b=b**2 # b raised to the power 2
print(b)

[1 2 3 4]
[ 4 16 36 64]


In [60]:
np.stack((a,b),axis=1) #columnwise stacking

array([[ 1,  4],
       [ 2, 16],
       [ 3, 36],
       [ 4, 64]])

In [64]:
a = np.stack((a,b),axis=0) #rowwise stacking

In [65]:
# Reshape a Numpy Array
print(a)

[[ 1  2  3  4]
 [ 4 16 36 64]]


In [66]:
#It has 8 elements. I want to make it as 4 rows and 2 columns.

In [67]:
a = a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 4 16]
 [36 64]]


In [68]:
a = a.reshape((8,1))
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 4]
 [16]
 [36]
 [64]]


In [69]:
a = a.reshape((8,))
print(a)

[ 1  2  3  4  4 16 36 64]


In [70]:
a = a.reshape((4,-1))
print(a)
#If you know the rows and  do not know the columns then just write -1 and it will figure out the number of columns by itself.

[[ 1  2]
 [ 3  4]
 [ 4 16]
 [36 64]]


In [71]:
a = a.reshape((-1,4))
print(a)

[[ 1  2  3  4]
 [ 4 16 36 64]]


### Numpy Random Module
- rand: Random values in a given shape.
- randn: Return a sample (or samples) from the "standard normal" distribution.
- randint: Return random integers from low (inclusive) to high (exclusive).
- random: Return random floats in the half-open interval [0.0,1.0)

- choice: Generates a random sample from a given 1-D array
- Shuffe: Shuffles the contends of a sequence

In [74]:
# Numpy Random Module is an important module when it comes to working with random distribution and random number. 

In [87]:
a = np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [96]:
np.random.seed(5)
np.random.shuffle(a)
print(a)

[ 9  5 10  8 12 14  6 11  7 13]


In [80]:
a = np.random.rand(2,3)
print(a)

[[0.923976   0.76435931 0.81534097]
 [0.409755   0.13466125 0.63953798]]


In [81]:
a = np.random.randn(2,3)
print(a)
#Returns values from a standard normal distribution

[[-1.94929482  1.42551514 -0.58632058]
 [ 0.77858803 -0.34968273  0.63301366]]


In [83]:
a = np.random.randint(5,10,2) # gives 2 numbers which are in range 5 to 10
print(a)

[7 9]


In [84]:
#Randomly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)

1


###  Some More Numpy Functions - Statistics
- min,max
- mean
- median
- average
- variance
- standard deviation

In [100]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [ ]:
print(np.min(a))

In [106]:
#Specify axis for the direction in case of multidim array
print(np.min(a, axis=0)) #min in all columns

[1 2 2 0]


In [107]:
print(np.min(a, axis=1))#min in all rows

[1 0]


In [111]:
# Mean, average all the elements
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))# mean along the columns
print(np.mean(a,axis=1))# mean along the rows

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [121]:
c = np.array([1,5,4,2,0])
print(np.median(c))

# Mean vs Average
print(np.mean(c))# Average is weighted average

# Weights
w = np.array([1,1,1,1,1])
print(np.average(c, weights=w))

# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#Inbuilt Function for Standard Deviation
dev = np.std(c)
print(dev)

#Variance
print(myStd**2)
print(np.var(c))

2.0
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004
