### 4. Broadcasting

- You can add scalar to a vector, and numpy will add it to each element in the vector

  x+a=xi+a
  
  
- Similarly you can add a vector to a matrix, and numpy will add the vector to each column of the matrix

In [9]:
import numpy as np
x = np.array([1,2,3,4])
print (x)
x = np.array([1,2,3,4])+5
print (x)
print(x+10) 
# Broadcasting
# Broadcasting is not supported with Python list
# [1,2,3,4] + 20

[1 2 3 4]
[6 7 8 9]
[16 17 18 19]


In [10]:
X = np.array([[10,20,30,40],[40,50,60,70]])
print(X+x)

[[16 27 38 49]
 [46 57 68 79]]


In [12]:
# Has various application in Neural Network. We will get equations like W.x + b.

### 5. Matrix Multiplication
This is perhaps one operation that you would use quite frequently in any ML/DL model. You should remember a few things about multiplication

- C=AB is only defined when the second dimension of A matches the first dimension of B
- Further, if A is of shape(m,n) and B of shape (n,p), then X is of shape(m,p)
- This operation is concretely defined as Ci,j = Sum of k Ai,k Bk,j
    - Ci,j is computed by taking the dot product of i-th row of A with j-th column of B
- A more useful method to think of matrix multiplication is as linear combination of columns of A weighted by column entries of B

There are two types of multiplication:
- Element wise
- Dot Product/ Matrix Multiplication

### 6. Element Wise Multiplication: Hadamard product
                               
Element wise multiplication A element wise multiplication B
                               
Notice how numpy uses the * for this. Important to be careful, and not to confuse this with matrix multiplication.

In [13]:
A = np.array([[1,2],
              [3,4]])

In [14]:
B = np.array([[0,2],
              [3,2]])

In [15]:
A*B

array([[0, 4],
       [9, 8]])

Matrix Multiplication O(N3)

In [16]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[0,2],
              [3,2]])
np.dot(A,B)

array([[ 6,  6],
       [12, 14]])

In [17]:
# 3 Blue and 1 Brown YouTube Channal

### 7. Norm

In [19]:
x = np.array([3,4])

In [20]:
lp2 = np.linalg.norm(x)

In [21]:
print(lp2)

5.0


In [22]:
lp1 = np.linalg.norm(x,ord=1)

In [23]:
lp1

7.0

In [24]:
lpinf = np.linalg.norm(x,ord=np.inf)

In [25]:
lpinf

4.0

### 8. Determinant

In [27]:
A = np.array([[1,2],
              [3,4]])

np.linalg.det(A)

-2.0000000000000004

In [28]:
# 1*4-2*3=-2

### 9. Inverse

In [32]:
Ainv = np.linalg.inv(A) 
# Ainv i.e. when a matrix A is multiplied with Ainv then the result should be 1. 
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [34]:
print(np.dot(A,Ainv)) #The result reduces to identity matrix i.e. A.A-1 = I

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [36]:
pinv = np.linalg.pinv(A) #pinv = pseudo inverse
print(pinv)
print(np.dot(A,pinv))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.0000000e+00 -4.4408921e-16]
 [ 8.8817842e-16  1.0000000e+00]]


In [39]:
# Let us assume that A is a non invertible matrix.
# i.e. A has 0 determinant.
# i.e. the inverse should exist with a different value as compared to the pseudo inverse.

In [40]:
A = np.array([[6,8],
              [3,4]])
pinv = np.linalg.pinv(A) #pinv = pseudo inverse
print(pinv)
print(np.dot(A,pinv))

[[0.048 0.024]
 [0.064 0.032]]
[[0.8 0.4]
 [0.4 0.2]]


### 10. Solve a System of Equations

In [43]:
# 2x1+3x2 = 8
# 3x1+1x2 = 5
#Find the vector x = (x1 x2)

In [44]:
# Ax=B
a = np.array([[2,3],[3,1]])
b = np.array([8,5])
np.linalg.solve(a,b)
#2 3 x1= 8
#3 1 x2= 5

array([1., 2.])

In [46]:
# i.e. x1=1, x2=2